onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /testbench/dut/xtlp_to_axi_master/sys_clk
add wave -noupdate /testbench/dut/xtlp_to_axi_master/sys_reset_n
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_in_valid
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_in_abort
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_in_accept_data
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_in_fmt_type
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_in_address
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_in_length_in_dw
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_in_attr
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_in_transaction_id
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_in_data
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_in_byte_en
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_in_byte_count
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_req_to_send
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_grant
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_fmt_type
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_length_in_dw
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_src_rdy_n
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_dst_rdy_n
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_data
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_address
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_ldwbe_fdwbe
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_attr
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_transaction_id
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_byte_count
add wave -noupdate /testbench/dut/xtlp_to_axi_master/tlp_out_lower_address
add wave -noupdate -color Gold -expand -subitemconfig {/testbench/dut/xtlp_to_axi_master/axi_window(3) {-color Gold -height 15 -expand} /testbench/dut/xtlp_to_axi_master/axi_window(3).ctrl {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(3).pci_bar0_start {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(3).pci_bar0_stop {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(3).axi_translation {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(2) {-color Gold -height 15 -expand} /testbench/dut/xtlp_to_axi_master/axi_window(2).ctrl {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(2).pci_bar0_start {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(2).pci_bar0_stop {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(2).axi_translation {-color Gold -height 15 -expand} /testbench/dut/xtlp_to_axi_master/axi_window(2).axi_translation.value {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(1) {-color Gold -height 15 -expand} /testbench/dut/xtlp_to_axi_master/axi_window(1).ctrl {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(1).pci_bar0_start {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(1).pci_bar0_stop {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(1).axi_translation {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(0) {-color Gold -height 15 -expand} /testbench/dut/xtlp_to_axi_master/axi_window(0).ctrl {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(0).pci_bar0_start {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(0).pci_bar0_stop {-color Gold -height 15} /testbench/dut/xtlp_to_axi_master/axi_window(0).axi_translation {-color Gold -height 15}} /testbench/dut/xtlp_to_axi_master/axi_window
add wave -noupdate /testbench/dut/xtlp_to_axi_master/sys_reset
add wave -noupdate /testbench/dut/xtlp_to_axi_master/nxtState
add wave -noupdate /testbench/dut/xtlp_to_axi_master/state
add wave -noupdate /testbench/dut/xtlp_to_axi_master/isWrite
add wave -noupdate /testbench/dut/xtlp_to_axi_master/hit_window
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_translated_address
add wave -noupdate /testbench/dut/xtlp_to_axi_master/dw_burst_counter
add wave -noupdate /testbench/dut/xtlp_to_axi_master/load_data
add wave -noupdate /testbench/dut/xtlp_to_axi_master/compl_req
add wave -noupdate /testbench/dut/xtlp_to_axi_master/compl_abort
add wave -noupdate /testbench/dut/xtlp_to_axi_master/COMPL_MAX_TIMEOUT
add wave -noupdate /testbench/dut/xtlp_to_axi_master/windowing_en
add wave -noupdate -color Gold /testbench/dut/xtlp_to_axi_master/hit_window
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_awid
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_awaddr
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_awlen
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_awvalid
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_wdata
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_wlast
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_wvalid
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_bready
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_araddr
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_arlen
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_arvalid
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_rready
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_aw_ack
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_w_ack
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_b_ack
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_ar_ack
add wave -noupdate /testbench/dut/xtlp_to_axi_master/axi_r_ack
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_AWREADY
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_AWVALID
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_AWADDR
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_AWLEN
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_AWSIZE
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_AWBURST
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_AWPROT
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_WREADY
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_WVALID
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_WDATA
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_WSTRB
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_WLAST
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_BVALID
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_BREADY
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_BRESP
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_ARREADY
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_ARVALID
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_ARADDR
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_ARLEN
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_ARSIZE
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_ARBURST
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_RVALID
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_RREADY
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_RRESP
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_RLAST
add wave -noupdate /testbench/dut/xtlp_to_axi_master/M_AXI_RDATA
add wave -noupdate /testbench/dut/cfg_interrupt_msixenable
add wave -noupdate /testbench/dut/M_AXI_RLAST
add wave -noupdate /testbench/dut/fpga_sub_minor_ver
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {50268700971 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 330
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 fs} {72511950002 fs}
