set_operating_conditions -grade industrial

## Power analysis
set_load 10.000 [all_outputs]
set_property LOAD 10 [get_ports {fixed_io_mio[0]}]
set_property LOAD 10 [get_ports {fixed_io_mio[10]}]
set_property LOAD 10 [get_ports {fixed_io_mio[11]}]
set_property LOAD 10 [get_ports {fixed_io_mio[12]}]
set_property LOAD 10 [get_ports {fixed_io_mio[13]}]
set_property LOAD 10 [get_ports {fixed_io_mio[14]}]
set_property LOAD 10 [get_ports {fixed_io_mio[15]}]
set_property LOAD 10 [get_ports {fixed_io_mio[16]}]
set_property LOAD 10 [get_ports {fixed_io_mio[17]}]
set_property LOAD 10 [get_ports {fixed_io_mio[18]}]
set_property LOAD 10 [get_ports {fixed_io_mio[19]}]
set_property LOAD 10 [get_ports {fixed_io_mio[1]}]
set_property LOAD 10 [get_ports {fixed_io_mio[20]}]
set_property LOAD 10 [get_ports {fixed_io_mio[21]}]
set_property LOAD 10 [get_ports {fixed_io_mio[22]}]
set_property LOAD 10 [get_ports {fixed_io_mio[23]}]
set_property LOAD 10 [get_ports {fixed_io_mio[24]}]
set_property LOAD 10 [get_ports {fixed_io_mio[25]}]
set_property LOAD 10 [get_ports {fixed_io_mio[26]}]
set_property LOAD 10 [get_ports {fixed_io_mio[27]}]
set_property LOAD 10 [get_ports {fixed_io_mio[28]}]
set_property LOAD 10 [get_ports {fixed_io_mio[29]}]
set_property LOAD 10 [get_ports {fixed_io_mio[2]}]
set_property LOAD 10 [get_ports {fixed_io_mio[30]}]
set_property LOAD 10 [get_ports {fixed_io_mio[31]}]
set_property LOAD 10 [get_ports {fixed_io_mio[32]}]
set_property LOAD 10 [get_ports {fixed_io_mio[33]}]
set_property LOAD 10 [get_ports {fixed_io_mio[34]}]
set_property LOAD 10 [get_ports {fixed_io_mio[35]}]
set_property LOAD 10 [get_ports {fixed_io_mio[36]}]
set_property LOAD 10 [get_ports {fixed_io_mio[37]}]
set_property LOAD 10 [get_ports {fixed_io_mio[38]}]
set_property LOAD 10 [get_ports {fixed_io_mio[39]}]
set_property LOAD 10 [get_ports {fixed_io_mio[3]}]
set_property LOAD 10 [get_ports {fixed_io_mio[40]}]
set_property LOAD 10 [get_ports {fixed_io_mio[41]}]
set_property LOAD 10 [get_ports {fixed_io_mio[42]}]
set_property LOAD 10 [get_ports {fixed_io_mio[43]}]
set_property LOAD 10 [get_ports {fixed_io_mio[44]}]
set_property LOAD 10 [get_ports {fixed_io_mio[45]}]
set_property LOAD 10 [get_ports {fixed_io_mio[46]}]
set_property LOAD 10 [get_ports {fixed_io_mio[47]}]
set_property LOAD 10 [get_ports {fixed_io_mio[48]}]
set_property LOAD 10 [get_ports {fixed_io_mio[49]}]
set_property LOAD 10 [get_ports {fixed_io_mio[4]}]
set_property LOAD 10 [get_ports {fixed_io_mio[50]}]
set_property LOAD 10 [get_ports {fixed_io_mio[51]}]
set_property LOAD 10 [get_ports {fixed_io_mio[52]}]
set_property LOAD 10 [get_ports {fixed_io_mio[53]}]
set_property LOAD 10 [get_ports {fixed_io_mio[5]}]
set_property LOAD 10 [get_ports {fixed_io_mio[6]}]
set_property LOAD 10 [get_ports {fixed_io_mio[7]}]
set_property LOAD 10 [get_ports {fixed_io_mio[8]}]
set_property LOAD 10 [get_ports {fixed_io_mio[9]}]
set_property LOAD 10 [get_ports fixed_io_ps_clk]
set_property LOAD 10 [get_ports fixed_io_ps_porb]
set_property LOAD 10 [get_ports fixed_io_ps_srstb]
set_property LOAD 10 [get_ports ncsi_clk_out]
set_property LOAD 10 [get_ports {pcie_txn[0]}]
set_property LOAD 10 [get_ports {pcie_txn[1]}]
set_property LOAD 10 [get_ports {pcie_txp[0]}]
set_property LOAD 10 [get_ports {pcie_txp[1]}]
set_property LOAD 10 [get_ports profinet_tx_en]
set_property LOAD 10 [get_ports {profinet_txd[0]}]
set_property LOAD 10 [get_ports {profinet_txd[1]}]
set_property LOAD 10 [get_ports uart_dtrn]
set_property LOAD 10 [get_ports uart_rtsn]
set_property LOAD 10 [get_ports uart_txd]
set_property LOAD 10 [get_ports {user_data_out[0]}]
set_property LOAD 10 [get_ports {user_data_out[1]}]
set_property LOAD 10 [get_ports {user_data_out[2]}]
set_property LOAD 10 [get_ports spi_cs_n]
set_property LOAD 10 [get_ports {spi_sd[0]}]
set_property LOAD 10 [get_ports {spi_sd[1]}]
set_property LOAD 10 [get_ports {spi_sd[2]}]
set_property LOAD 10 [get_ports {spi_sd[3]}]
set_operating_conditions -ambient_temp 85.0
set_operating_conditions -board_layers 8to11
set_operating_conditions -board small
set_operating_conditions -heatsink high

