onerror {resume}
quietly virtual signal -install /testbench/DUT/xdpc_filter { (context /testbench/DUT/xdpc_filter )( s_axis_tdata(79 downto 72) & s_axis_tdata(69 downto 62) & s_axis_tdata(59 downto 52) & s_axis_tdata(49 downto 42) & s_axis_tdata(39 downto 32) & s_axis_tdata(29 downto 22) & s_axis_tdata(19 downto 12) & s_axis_tdata(9 downto 2) )} s_axis_tdata8
quietly virtual signal -install /testbench/DUT/xdpc_filter { (context /testbench/DUT/xdpc_filter )( m_axis_tdata(79 downto 72) & m_axis_tdata(69 downto 62) & m_axis_tdata(59 downto 52) & m_axis_tdata(49 downto 42) & m_axis_tdata(39 downto 32) & m_axis_tdata(29 downto 22) & m_axis_tdata(19 downto 12) & m_axis_tdata(9 downto 2) )} m_axis_tdata8
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider DCP_RX
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_tvalid
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_tready
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_tuser
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_tlast
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_tdata
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_tdata8
add wave -noupdate -divider DCP_TX
add wave -noupdate /testbench/DUT/xdpc_filter/m_axis_tready
add wave -noupdate /testbench/DUT/xdpc_filter/m_axis_tvalid
add wave -noupdate /testbench/DUT/xdpc_filter/m_axis_tuser
add wave -noupdate /testbench/DUT/xdpc_filter/m_axis_tlast
add wave -noupdate /testbench/DUT/xdpc_filter/m_axis_tdata
add wave -noupdate /testbench/DUT/xdpc_filter/m_axis_tdata8
add wave -noupdate -divider TX_AXI
add wave -noupdate -color {Medium Violet Red} /testbench/inst_pcie_tx_axi/s_axis_tx_tvalid
add wave -noupdate -color {Medium Violet Red} /testbench/inst_pcie_tx_axi/s_axis_tx_tuser
add wave -noupdate -color {Medium Violet Red} /testbench/inst_pcie_tx_axi/s_axis_tx_tready
add wave -noupdate -color {Medium Violet Red} /testbench/inst_pcie_tx_axi/s_axis_tx_tlast
add wave -noupdate -color {Medium Violet Red} /testbench/inst_pcie_tx_axi/s_axis_tx_tkeep
add wave -noupdate -color {Medium Violet Red} /testbench/inst_pcie_tx_axi/s_axis_tx_tdata
add wave -noupdate -divider <NULL>
add wave -noupdate /testbench/DUT/xdpc_filter/axi_clk
add wave -noupdate /testbench/DUT/xdpc_filter/axi_reset_n
add wave -noupdate /testbench/DUT/xdpc_filter/curr_Xstart
add wave -noupdate /testbench/DUT/xdpc_filter/curr_Xend
add wave -noupdate /testbench/DUT/xdpc_filter/curr_Ystart
add wave -noupdate /testbench/DUT/xdpc_filter/curr_Yend
add wave -noupdate /testbench/DUT/xdpc_filter/curr_Xsub
add wave -noupdate /testbench/DUT/xdpc_filter/curr_Ysub
add wave -noupdate /testbench/DUT/xdpc_filter/load_dma_context_EOFOT
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_list_length
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_ver
add wave -noupdate /testbench/DUT/xdpc_filter/REG_color
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_enable
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_pattern0_cfg
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_fifo_rst
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_fifo_ovr
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_fifo_und
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_list_wrn
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_list_add
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_list_ss
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_list_count
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_list_corr_pattern
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_list_corr_y
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_list_corr_x
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_list_corr_rd
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_firstlast_line_rem
add wave -noupdate /testbench/DUT/xdpc_filter/axi_reset
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_tready_int
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_first_line
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_first_prefetch
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_prefetch
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_prefetch_done
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_prefetch_cnt
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_line_gap
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_line_wait
add wave -noupdate /testbench/DUT/xdpc_filter/s_axis_frame_done
add wave -noupdate /testbench/DUT/xdpc_filter/curr_Xstart_corr
add wave -noupdate /testbench/DUT/xdpc_filter/curr_Xend_corr
add wave -noupdate /testbench/DUT/xdpc_filter/curr_Xstart_integer
add wave -noupdate /testbench/DUT/xdpc_filter/curr_Xend_integer
add wave -noupdate /testbench/DUT/xdpc_filter/BAYER_Sensor
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_enable_P1
add wave -noupdate /testbench/DUT/xdpc_filter/REG_dpc_enable_DB
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_sol_P1
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_data_enable_start
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_data_enable_stop
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_data_enable_P1
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_data_bypass
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_data_in_100_P1
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_data_in_100_P2
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_eol_P1
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_eol_P2
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_eol_P3
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_eof_P1
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_eof_P2
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_eof_P3
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_eof_P4
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_kernel_10x3_sof
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_kernel_10x3_sol
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_kernel_10x3_eol
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_kernel_10x3_eof
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_sof
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_sol
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_eol
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_en
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_out
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_eof
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_curr
add wave -noupdate /testbench/DUT/xdpc_filter/proc_X_pix_curr_nosub
add wave -noupdate /testbench/DUT/xdpc_filter/proc_X_pix_curr_sub
add wave -noupdate /testbench/DUT/xdpc_filter/proc_X_pix_curr
add wave -noupdate /testbench/DUT/xdpc_filter/proc_first_col
add wave -noupdate /testbench/DUT/xdpc_filter/proc_last_col
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_sof_P1
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_sol_P1
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_en_P1
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_eol_P1
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_eof_P1
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_sol_P2
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_en_P2
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_eol_P2
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_eof_P2
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_sol_P3
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_en_P3
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_eol_P3
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_eof_P3
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_sol_P4
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_en_P4
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_eol_P4
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_eof_P4
add wave -noupdate /testbench/DUT/xdpc_filter/proc_sol
add wave -noupdate /testbench/DUT/xdpc_filter/proc_en
add wave -noupdate /testbench/DUT/xdpc_filter/proc_data
add wave -noupdate /testbench/DUT/xdpc_filter/proc_eol
add wave -noupdate /testbench/DUT/xdpc_filter/proc_eof
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_first_line
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_last_line
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_first_col
add wave -noupdate /testbench/DUT/xdpc_filter/kernel_10x3_last_col
add wave -noupdate /testbench/DUT/xdpc_filter/Pix_corr
add wave -noupdate /testbench/DUT/xdpc_filter/Pix_corr_sof
add wave -noupdate /testbench/DUT/xdpc_filter/Pix_corr_sol
add wave -noupdate /testbench/DUT/xdpc_filter/Pix_corr_en
add wave -noupdate /testbench/DUT/xdpc_filter/Pix_corr_eol
add wave -noupdate /testbench/DUT/xdpc_filter/Pix_corr_eof
add wave -noupdate /testbench/DUT/xdpc_filter/RAM_R_enable
add wave -noupdate /testbench/DUT/xdpc_filter/RAM_R_enable_P1
add wave -noupdate /testbench/DUT/xdpc_filter/RAM_R_address
add wave -noupdate /testbench/DUT/xdpc_filter/RAM_R_data
add wave -noupdate /testbench/DUT/xdpc_filter/RAM_R_end
add wave -noupdate /testbench/DUT/xdpc_filter/RAM_R_end_P1
add wave -noupdate /testbench/DUT/xdpc_filter/RAM_W_data
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_fifo_reset
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_fifo_reset_P1
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_fifo_reset_P2
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_fifo_reset_P3
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_fifo_reset_P4
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_fifo_reset_P5
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_fifo_data
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_fifo_write
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_fifo_list_rdy
add wave -noupdate /testbench/DUT/xdpc_filter/dpc_fifo_reset_done
add wave -noupdate /testbench/DUT/xdpc_filter/m_axis_tvalid_int
add wave -noupdate /testbench/DUT/xdpc_filter/m_axis_tdata_int
add wave -noupdate /testbench/DUT/xdpc_filter/m_axis_tuser_int
add wave -noupdate /testbench/DUT/xdpc_filter/m_axis_wait_data
add wave -noupdate /testbench/DUT/xdpc_filter/m_axis_wait
add wave -noupdate /testbench/DUT/xdpc_filter/alias_proc_data_3
add wave -noupdate /testbench/DUT/xdpc_filter/alias_proc_data_2
add wave -noupdate /testbench/DUT/xdpc_filter/alias_proc_data_1
add wave -noupdate /testbench/DUT/xdpc_filter/alias_proc_data_0
add wave -noupdate /testbench/DUT/xdpc_filter/alias_dpc_data_in_100_4_P2
add wave -noupdate /testbench/DUT/xdpc_filter/alias_dpc_data_in_100_3_P2
add wave -noupdate /testbench/DUT/xdpc_filter/alias_dpc_data_in_100_2_P2
add wave -noupdate /testbench/DUT/xdpc_filter/alias_dpc_data_in_100_1_P2
add wave -noupdate /testbench/DUT/xdpc_filter/alias_dpc_data_in_100_0_P2
add wave -noupdate /testbench/DUT/xdpc_filter/alias_dpc_data_in_100_L_P2
add wave -noupdate /testbench/DUT/xdpc_filter/alias_dpc_data_in_100_3_P1
add wave -noupdate /testbench/DUT/xdpc_filter/alias_dpc_data_in_100_2_P1
add wave -noupdate /testbench/DUT/xdpc_filter/alias_dpc_data_in_100_1_P1
add wave -noupdate /testbench/DUT/xdpc_filter/alias_dpc_data_in_100_0_P1
add wave -noupdate /testbench/DUT/xdpc_filter/alias_fpnprnu_corr_data_3
add wave -noupdate /testbench/DUT/xdpc_filter/alias_fpnprnu_corr_data_2
add wave -noupdate /testbench/DUT/xdpc_filter/alias_fpnprnu_corr_data_1
add wave -noupdate /testbench/DUT/xdpc_filter/alias_fpnprnu_corr_data_0
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1696184000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 191
configure wave -valuecolwidth 160
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {1172866963 ps} {2284864245 ps}
