##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Fri Oct 21 13:04:22 2016
##  Generated by MIG Version 2.3
##  
##################################################################################################
##  File name :       ddr2.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A35T-FGGcpg236
##                    Speedgrade:        -1
##                    Design Entry:      VERILOG
##                    Frequency:         0 MHz
##                    Time Period:       5000 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR2_SDRAM->Components->mt47h32m16en8
## Data Width: 8
## Time Period: 5000
## Data Mask: 1
##################################################################################################

#create_clock -period 20 [get_ports sys_clk_i]

#create_clock -period 5 [get_ports clk_ref_i]

############## NET - IOSTANDARD ##################

##################################################################################################
## The selected data width is not a multiple of 16. Please note that MIG wizard is not taking care 
## of the 8 floating pins left on the external memory device.
##################################################################################################

# PadFunction: IO_L7N_T1_D10_14 
set_property SLEW FAST [get_ports {ddr2_dq[0]}]
set_property IN_TERM NONE [get_ports {ddr2_dq[0]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[0]}]
set_property PACKAGE_PIN J18 [get_ports {ddr2_dq[0]}]

# PadFunction: IO_L8P_T1_D11_14 
set_property SLEW FAST [get_ports {ddr2_dq[1]}]
set_property IN_TERM NONE [get_ports {ddr2_dq[1]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[1]}]
set_property PACKAGE_PIN L18 [get_ports {ddr2_dq[1]}]

# PadFunction: IO_L8N_T1_D12_14 
set_property SLEW FAST [get_ports {ddr2_dq[2]}]
set_property IN_TERM NONE [get_ports {ddr2_dq[2]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[2]}]
set_property PACKAGE_PIN K18 [get_ports {ddr2_dq[2]}]

# PadFunction: IO_L10P_T1_D14_14 
set_property SLEW FAST [get_ports {ddr2_dq[3]}]
set_property IN_TERM NONE [get_ports {ddr2_dq[3]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[3]}]
set_property PACKAGE_PIN P19 [get_ports {ddr2_dq[3]}]

# PadFunction: IO_L10N_T1_D15_14 
set_property SLEW FAST [get_ports {ddr2_dq[4]}]
set_property IN_TERM NONE [get_ports {ddr2_dq[4]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[4]}]
set_property PACKAGE_PIN R19 [get_ports {ddr2_dq[4]}]

# PadFunction: IO_L11P_T1_SRCC_14 
set_property SLEW FAST [get_ports {ddr2_dq[5]}]
set_property IN_TERM NONE [get_ports {ddr2_dq[5]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[5]}]
set_property PACKAGE_PIN M18 [get_ports {ddr2_dq[5]}]

# PadFunction: IO_L11N_T1_SRCC_14 
set_property SLEW FAST [get_ports {ddr2_dq[6]}]
set_property IN_TERM NONE [get_ports {ddr2_dq[6]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[6]}]
set_property PACKAGE_PIN M19 [get_ports {ddr2_dq[6]}]

# PadFunction: IO_L12N_T1_MRCC_14 
set_property SLEW FAST [get_ports {ddr2_dq[7]}]
set_property IN_TERM NONE [get_ports {ddr2_dq[7]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dq[7]}]
set_property PACKAGE_PIN K17 [get_ports {ddr2_dq[7]}]

# PadFunction: IO_L19P_T3_A10_D26_14 
set_property SLEW SLOW [get_ports {ddr2_addr[12]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[12]}]
set_property PACKAGE_PIN V16 [get_ports {ddr2_addr[12]}]

# PadFunction: IO_L19N_T3_A09_D25_VREF_14 
set_property SLEW SLOW [get_ports {ddr2_addr[11]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[11]}]
set_property PACKAGE_PIN V17 [get_ports {ddr2_addr[11]}]

# PadFunction: IO_L20P_T3_A08_D24_14 
set_property SLEW SLOW [get_ports {ddr2_addr[10]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[10]}]
set_property PACKAGE_PIN W16 [get_ports {ddr2_addr[10]}]

# PadFunction: IO_L20N_T3_A07_D23_14 
set_property SLEW SLOW [get_ports {ddr2_addr[9]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[9]}]
set_property PACKAGE_PIN W17 [get_ports {ddr2_addr[9]}]

# PadFunction: IO_L2P_T0_D02_14 
set_property SLEW SLOW [get_ports {ddr2_addr[8]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[8]}]
set_property PACKAGE_PIN G18 [get_ports {ddr2_addr[8]}]

# PadFunction: IO_L2N_T0_D03_14 
set_property SLEW SLOW [get_ports {ddr2_addr[7]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[7]}]
set_property PACKAGE_PIN F18 [get_ports {ddr2_addr[7]}]

# PadFunction: IO_L21P_T3_DQS_14 
set_property SLEW SLOW [get_ports {ddr2_addr[6]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[6]}]
set_property PACKAGE_PIN V15 [get_ports {ddr2_addr[6]}]

# PadFunction: IO_L21N_T3_DQS_A06_D22_14 
set_property SLEW SLOW [get_ports {ddr2_addr[5]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[5]}]
set_property PACKAGE_PIN W15 [get_ports {ddr2_addr[5]}]

# PadFunction: IO_L23P_T3_A03_D19_14 
set_property SLEW SLOW [get_ports {ddr2_addr[4]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[4]}]
set_property PACKAGE_PIN U15 [get_ports {ddr2_addr[4]}]

# PadFunction: IO_L23N_T3_A02_D18_14 
set_property SLEW SLOW [get_ports {ddr2_addr[3]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[3]}]
set_property PACKAGE_PIN U16 [get_ports {ddr2_addr[3]}]

# PadFunction: IO_L24P_T3_A01_D17_14 
set_property SLEW SLOW [get_ports {ddr2_addr[2]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[2]}]
set_property PACKAGE_PIN V13 [get_ports {ddr2_addr[2]}]

# PadFunction: IO_L24N_T3_A00_D16_14 
set_property SLEW SLOW [get_ports {ddr2_addr[1]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[1]}]
set_property PACKAGE_PIN V14 [get_ports {ddr2_addr[1]}]

# PadFunction: IO_25_14 
set_property SLEW SLOW [get_ports {ddr2_addr[0]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_addr[0]}]
set_property PACKAGE_PIN U14 [get_ports {ddr2_addr[0]}]

# PadFunction: IO_L3N_T0_DQS_EMCCLK_14 
set_property SLEW SLOW [get_ports {ddr2_ba[1]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_ba[1]}]
set_property PACKAGE_PIN E19 [get_ports {ddr2_ba[1]}]

# PadFunction: IO_L4P_T0_D04_14 
set_property SLEW SLOW [get_ports {ddr2_ba[0]}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_ba[0]}]
set_property PACKAGE_PIN H19 [get_ports {ddr2_ba[0]}]

# PadFunction: IO_L4N_T0_D05_14 
set_property SLEW SLOW [get_ports {ddr2_ras_n}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_ras_n}]
set_property PACKAGE_PIN G19 [get_ports {ddr2_ras_n}]

# PadFunction: IO_L5P_T0_D06_14 
set_property SLEW SLOW [get_ports {ddr2_cas_n}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_cas_n}]
set_property PACKAGE_PIN H17 [get_ports {ddr2_cas_n}]

# PadFunction: IO_L5N_T0_D07_14 
set_property SLEW SLOW [get_ports {ddr2_we_n}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_we_n}]
set_property PACKAGE_PIN G17 [get_ports {ddr2_we_n}]

# PadFunction: IO_0_14 
set_property SLEW SLOW [get_ports {ddr2_cke}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_cke}]
set_property PACKAGE_PIN D17 [get_ports {ddr2_cke}]

# PadFunction: IO_L6N_T0_D08_VREF_14 
set_property SLEW SLOW [get_ports {ddr2_odt}]
set_property IOSTANDARD SSTL18_I [get_ports {ddr2_odt}]
set_property PACKAGE_PIN J19 [get_ports {ddr2_odt}]

# PadFunction: IO_L7P_T1_D09_14 
set_property SLEW FAST [get_ports {ddr2_dm[0]}]
set_property IOSTANDARD SSTL18_II [get_ports {ddr2_dm[0]}]
set_property PACKAGE_PIN J17 [get_ports {ddr2_dm[0]}]

# PadFunction: IO_L9P_T1_DQS_14 
set_property SLEW FAST [get_ports {ddr2_dqs_p[0]}]
set_property IN_TERM NONE [get_ports {ddr2_dqs_p[0]}]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddr2_dqs_p[0]}]
set_property PACKAGE_PIN N18 [get_ports {ddr2_dqs_p[0]}]

# PadFunction: IO_L9N_T1_DQS_D13_14 
set_property SLEW FAST [get_ports {ddr2_dqs_n[0]}]
set_property IN_TERM NONE [get_ports {ddr2_dqs_n[0]}]
set_property IOSTANDARD DIFF_SSTL18_II [get_ports {ddr2_dqs_n[0]}]
set_property PACKAGE_PIN N19 [get_ports {ddr2_dqs_n[0]}]

# PadFunction: IO_L22P_T3_A05_D21_14 
set_property SLEW FAST [get_ports {ddr2_ck_p}]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports {ddr2_ck_p}]
set_property PACKAGE_PIN W13 [get_ports {ddr2_ck_p}]

# PadFunction: IO_L22N_T3_A04_D20_14 
set_property SLEW FAST [get_ports {ddr2_ck_n}]
set_property IOSTANDARD DIFF_SSTL18_I [get_ports {ddr2_ck_n}]
set_property PACKAGE_PIN W14 [get_ports {ddr2_ck_n}]


set_property INTERNAL_VREF  0.900 [get_iobanks 14]

set_property LOC PHASER_OUT_PHY_X0Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_out}]
set_property LOC PHASER_OUT_PHY_X0Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_out}]

## set_property LOC PHASER_IN_PHY_X0Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/phaser_in_gen.phaser_in}]
## set_property LOC PHASER_IN_PHY_X0Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/phaser_in_gen.phaser_in}]
set_property LOC PHASER_IN_PHY_X0Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/phaser_in_gen.phaser_in}]



set_property LOC OUT_FIFO_X0Y3 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_D.ddr_byte_lane_D/out_fifo}]
set_property LOC OUT_FIFO_X0Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_A.ddr_byte_lane_A/out_fifo}]
set_property LOC OUT_FIFO_X0Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/out_fifo}]

set_property LOC IN_FIFO_X0Y2 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/in_fifo_gen.in_fifo}]

set_property LOC PHY_CONTROL_X0Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phy_control_i}]

set_property LOC PHASER_REF_X0Y0 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/phaser_ref_i}]

set_property LOC OLOGIC_X0Y31 [get_cells  -hier -filter {NAME =~ */ddr_phy_4lanes_0.u_ddr_phy_4lanes/ddr_byte_lane_C.ddr_byte_lane_C/ddr_byte_group_io/*slave_ts}]

set_property LOC PLLE2_ADV_X0Y0 [get_cells -hier -filter {NAME =~ */u_ddr2_infrastructure/plle2_i}]
set_property LOC MMCME2_ADV_X0Y0 [get_cells -hier -filter {NAME =~ */u_ddr2_infrastructure/gen_mmcm.mmcm_i}]


set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] \
                    -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] \
                    -setup 6

set_multicycle_path -from [get_cells -hier -filter {NAME =~ */mc0/mc_read_idle_r_reg}] \
                    -to   [get_cells -hier -filter {NAME =~ */input_[?].iserdes_dq_.iserdesdq}] \
                    -hold 5



set_false_path -through [get_pins -filter {NAME =~ */DQSFOUND} -of [get_cells -hier -filter {REF_NAME == PHASER_IN_PHY}]]

set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -setup 2 -start
set_multicycle_path -through [get_pins -filter {NAME =~ */OSERDESRST} -of [get_cells -hier -filter {REF_NAME == PHASER_OUT_PHY}]] -hold 1 -start

set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/* && IS_SEQUENTIAL}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/device_temp_sync_r1*}] 20
set_max_delay -from [get_cells -hier *rstdiv0_sync_r1_reg*] -to [get_pins -filter {NAME =~ */RESET} -of [get_cells -hier -filter {REF_NAME == PHY_CONTROL}]] -datapath_only 5

set_max_delay -datapath_only -from [get_cells -hier -filter {NAME =~ *ddr2_infrastructure/rstdiv0_sync_r1_reg*}] -to [get_cells -hier -filter {NAME =~ *temp_mon_enabled.u_tempmon/xadc_supplied_temperature.rst_r1*}] 20
