/**
 * Filelist: sve.f
 */
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/image
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation/src
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/athena
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/fdkide
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/drivers
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/xgs_sensor
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation2/src
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/core
${workspace_loc}/athena/local_ip/XGS_athena/validation/src/Ctest0000.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation/src/glbl.v
${workspace_loc}/athena/local_ip/XGS_athena/validation/src/hispi_interface.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation/src/testbench.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation/src/tlp_interface.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation/src/xgs_athena_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/CVlib.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/Cimage.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/Cscoreboard.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/athena/athena_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/core/Cstatus.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/core/Ctest.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/core/core_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/core_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/drivers/driver_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/fdkide/fdkide_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/glbl.v
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/image/image_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/interfaces/axi_lite_interface.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/interfaces/axi_stream_interface.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/interfaces/hispi_interface.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/interfaces/io_interface.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/interfaces/tlp_interface.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/system_top.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/testbench.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/testbench_x_trim.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0001.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0002.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0003.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0004.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0005.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0006.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0007.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0008.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0009.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0010.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0020.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0021.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test2000.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test9999.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/xgs_athena_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/xgs_sensor/xgs_pkg.sv

