/**
 * Filelist: sve.f
*/
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/athena
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/xgs_sensor
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/drivers
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/fdkide
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/validation2/src
+incdir+${workspace_loc}/athena/local_ip/XGS_athena/registerfile
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/xgs_sensor/Cxgs_sensor.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/xgs_sensor/xgs_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/athena/Cathena.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/athena/athena_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/fdkide/fdkide_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/fdkide/Cnode.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/fdkide/Cfield.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/fdkide/Cregister.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/fdkide/Cexternal.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/fdkide/Csection.svh
${workspace_loc}/athena/local_ip/XGS_athena/registerfile/regfile_xgs_athena.sv
${workspace_loc}/athena/local_ip/XGS_athena/hdl/data/phy/hispi_phy_xilinx/hispi_phy_xilinx.v
${workspace_loc}/athena/local_ip/XGS_athena/hdl/data/phy/hispi_phy_xilinx/hispi_phy_xilinx_selectio_wiz.v
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/CVlib.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/core_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/drivers/driver_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/glbl.v
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/interfaces/axi_lite_interface.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/interfaces/axi_stream_interface.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/interfaces/hispi_interface.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/interfaces/io_interface.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/interfaces/tlp_interface.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/system_top.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/testbench.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0001.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0002.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test0003.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests/test2000.svh
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/tests_pkg.sv
${workspace_loc}/athena/local_ip/XGS_athena/validation2/src/xgs_athena_pkg.sv

