set_location_assignment PIN_W9 -to TMS_0
set_location_assignment PIN_V10 -to PROGRAM_B_0
set_location_assignment PIN_V11 -to CFGBVS_0
set_location_assignment PIN_U10 -to M2_0
set_location_assignment PIN_W8 -to TDO_0
set_location_assignment PIN_W10 -to TDI_0
set_location_assignment PIN_U11 -to INIT_B_0
set_location_assignment PIN_W11 -to M1_0
set_location_assignment PIN_V12 -to M0_0
set_location_assignment PIN_C11 -to CCLK_0
set_location_assignment PIN_A13 -to VREFN_0
set_location_assignment PIN_B11 -to DXN_0
set_location_assignment PIN_C8 -to TCK_0
set_location_assignment PIN_C9 -to VCCBATT_0
set_location_assignment PIN_B12 -to VREFP_0
set_location_assignment PIN_C13 -to VCCADC_0
set_location_assignment PIN_C12 -to GNDADC_0
set_location_assignment PIN_A11 -to DXP_0
set_location_assignment PIN_U12 -to DONE_0
set_location_assignment PIN_A12 -to VP_0
set_location_assignment PIN_B13 -to VN_0
set_location_assignment PIN_J13 -to VCCAUX_J13
set_location_assignment PIN_H13 -to VCCAUX_H13
set_location_assignment PIN_N11 -to VCCBRAM_N11
set_location_assignment PIN_M11 -to VCCBRAM_M11
set_location_assignment PIN_N10 -to VCCINT_N10
set_location_assignment PIN_M10 -to VCCINT_M10
set_location_assignment PIN_L10 -to VCCINT_L10
set_location_assignment PIN_J10 -to VCCINT_J10
set_location_assignment PIN_H10 -to VCCINT_H10
set_location_assignment PIN_G10 -to VCCINT_G10
set_location_assignment PIN_M7 -to VCCO_35_M7
set_location_assignment PIN_L7 -to VCCO_35_L7
set_location_assignment PIN_K7 -to VCCO_35_K7
set_location_assignment PIN_K1 -to VCCO_35_K1
set_location_assignment PIN_J7 -to VCCO_35_J7
set_location_assignment PIN_H3 -to VCCO_35_H3
set_location_assignment PIN_V6 -to VCCO_34_V6
set_location_assignment PIN_V1 -to VCCO_34_V1
set_location_assignment PIN_R1 -to VCCO_34_R1
set_location_assignment PIN_N8 -to VCCO_34_N8
set_location_assignment PIN_N7 -to VCCO_34_N7
set_location_assignment PIN_M8 -to VCCO_34_M8
set_location_assignment PIN_G13 -to VCCO_16_G13
set_location_assignment PIN_C18 -to VCCO_16_C18
set_location_assignment PIN_C14 -to VCCO_16_C14
set_location_assignment PIN_B19 -to VCCO_16_B19
set_location_assignment PIN_U13 -to VCCO_14_U13
set_location_assignment PIN_R17 -to VCCO_14_R17
set_location_assignment PIN_M17 -to VCCO_14_M17
set_location_assignment PIN_M12 -to VCCO_14_M12
set_location_assignment PIN_L13 -to VCCO_14_L13
set_location_assignment PIN_L12 -to VCCO_14_L12
set_location_assignment PIN_K13 -to VCCO_14_K13
set_location_assignment PIN_K12 -to VCCO_14_K12
set_location_assignment PIN_F17 -to VCCO_14_F17
set_location_assignment PIN_G12 -to VCCO_0_G12
set_location_assignment PIN_V9 -to VCCO_0_V9
set_location_assignment PIN_W12 -to GND_W12
set_location_assignment PIN_W1 -to GND_W1
set_location_assignment PIN_V18 -to GND_V18
set_location_assignment PIN_U9 -to GND_U9
set_location_assignment PIN_U6 -to GND_U6
set_location_assignment PIN_T19 -to GND_T19
set_location_assignment PIN_P2 -to GND_P2
set_location_assignment PIN_N13 -to GND_N13
set_location_assignment PIN_N12 -to GND_N12
set_location_assignment PIN_N9 -to GND_N9
set_location_assignment PIN_M13 -to GND_M13
set_location_assignment PIN_M9 -to GND_M9
set_location_assignment PIN_L19 -to GND_L19
set_location_assignment PIN_L11 -to GND_L11
set_location_assignment PIN_L9 -to GND_L9
set_location_assignment PIN_L8 -to GND_L8
set_location_assignment PIN_K8 -to GND_K8
set_location_assignment PIN_J12 -to GND_J12
set_location_assignment PIN_J11 -to GND_J11
set_location_assignment PIN_J9 -to GND_J9
set_location_assignment PIN_J8 -to GND_J8
set_location_assignment PIN_H18 -to GND_H18
set_location_assignment PIN_H12 -to GND_H12
set_location_assignment PIN_H11 -to GND_H11
set_location_assignment PIN_H8 -to GND_H8
set_location_assignment PIN_H7 -to GND_H7
set_location_assignment PIN_G11 -to GND_G11
set_location_assignment PIN_G8 -to GND_G8
set_location_assignment PIN_G1 -to GND_G1
set_location_assignment PIN_F19 -to GND_F19
set_location_assignment PIN_F2 -to GND_F2
set_location_assignment PIN_F1 -to GND_F1
set_location_assignment PIN_E17 -to GND_E17
set_location_assignment PIN_E3 -to GND_E3
set_location_assignment PIN_D3 -to GND_D3
set_location_assignment PIN_C19 -to GND_C19
set_location_assignment PIN_C10 -to GND_C10
set_location_assignment PIN_C6 -to GND_C6
set_location_assignment PIN_C4 -to GND_C4
set_location_assignment PIN_C3 -to GND_C3
set_location_assignment PIN_C2 -to GND_C2
set_location_assignment PIN_B14 -to GND_B14
set_location_assignment PIN_B9 -to GND_B9
set_location_assignment PIN_B7 -to GND_B7
set_location_assignment PIN_B5 -to GND_B5
set_location_assignment PIN_B3 -to GND_B3
set_location_assignment PIN_A19 -to GND_A19
set_location_assignment PIN_A9 -to GND_A9
set_location_assignment PIN_A7 -to GND_A7
set_location_assignment PIN_A5 -to GND_A5
set_location_assignment PIN_A3 -to GND_A3
set_location_assignment PIN_A1 -to GND_A1
set_location_assignment PIN_C17 -to IO_L14P_T2_SRCC_16
set_location_assignment PIN_C16 -to IO_L13P_T2_MRCC_16
set_location_assignment PIN_A15 -to IO_L6N_T0_VREF_16
set_location_assignment PIN_C15 -to smbdata
set_location_assignment PIN_A14 -to temp_alertN
set_location_assignment PIN_B15 -to smbclk
set_location_assignment PIN_A18 -to xgs_power_good
set_location_assignment PIN_B16 -to sys_rst_n
set_location_assignment PIN_A16 -to debug_data[0]
set_location_assignment PIN_A17 -to debug_data[1]
set_location_assignment PIN_B17 -to debug_data[2]
set_location_assignment PIN_B18 -to debug_data[3]
set_location_assignment PIN_U14 -to IO_25_14
set_location_assignment PIN_V14 -to IO_L24N_T3_A00_D16_14
set_location_assignment PIN_V13 -to IO_L24P_T3_A01_D17_14
set_location_assignment PIN_U16 -to IO_L23N_T3_A02_D18_14
set_location_assignment PIN_U15 -to IO_L23P_T3_A03_D19_14
set_location_assignment PIN_W14 -to IO_L22N_T3_A04_D20_14
set_location_assignment PIN_W13 -to IO_L22P_T3_A05_D21_14
set_location_assignment PIN_W15 -to IO_L21N_T3_DQS_A06_D22_14
set_location_assignment PIN_V15 -to IO_L21P_T3_DQS_14
set_location_assignment PIN_W17 -to IO_L20N_T3_A07_D23_14
set_location_assignment PIN_W16 -to IO_L20P_T3_A08_D24_14
set_location_assignment PIN_V17 -to IO_L19N_T3_A09_D25_VREF_14
set_location_assignment PIN_V16 -to IO_L19P_T3_A10_D26_14
set_location_assignment PIN_U18 -to IO_L18N_T2_A11_D27_14
set_location_assignment PIN_U17 -to IO_L18P_T2_A12_D28_14
set_location_assignment PIN_T18 -to IO_L17N_T2_A13_D29_14
set_location_assignment PIN_T17 -to IO_L17P_T2_A14_D30_14
set_location_assignment PIN_W19 -to IO_L16N_T2_A15_D31_14
set_location_assignment PIN_W18 -to IO_L16P_T2_CSI_B_14
set_location_assignment PIN_V19 -to IO_L15N_T2_DQS_DOUT_CSO_B_14
set_location_assignment PIN_U19 -to IO_L15P_T2_DQS_RDWR_B_14
set_location_assignment PIN_R18 -to IO_L14N_T2_SRCC_14
set_location_assignment PIN_P18 -to IO_L14P_T2_SRCC_14
set_location_assignment PIN_P17 -to IO_L13N_T2_MRCC_14
set_location_assignment PIN_N17 -to IO_L13P_T2_MRCC_14
set_location_assignment PIN_K17 -to IO_L12N_T1_MRCC_14
set_location_assignment PIN_L17 -to IO_L12P_T1_MRCC_14
set_location_assignment PIN_M19 -to IO_L11N_T1_SRCC_14
set_location_assignment PIN_M18 -to IO_L11P_T1_SRCC_14
set_location_assignment PIN_R19 -to IO_L10N_T1_D15_14
set_location_assignment PIN_P19 -to IO_L10P_T1_D14_14
set_location_assignment PIN_N19 -to IO_L9N_T1_DQS_D13_14
set_location_assignment PIN_N18 -to IO_L9P_T1_DQS_14
set_location_assignment PIN_K18 -to IO_L8N_T1_D12_14
set_location_assignment PIN_L18 -to IO_L8P_T1_D11_14
set_location_assignment PIN_J19 -to IO_L6N_T0_D08_VREF_14
set_location_assignment PIN_H17 -to fpga_var_type[1]
set_location_assignment PIN_G17 -to fpga_var_type[0]
set_location_assignment PIN_E18 -to IO_L3P_T0_DQS_PUDC_B_14
set_location_assignment PIN_H19 -to exposure_out
set_location_assignment PIN_G19 -to strobe_out
set_location_assignment PIN_J18 -to trig_rdy_out
set_location_assignment PIN_J17 -to ext_trig
set_location_assignment PIN_D17 -to led_out[1]
set_location_assignment PIN_E19 -to led_out[0]
set_location_assignment PIN_F18 -to cfg_spi_sd[3]
set_location_assignment PIN_G18 -to cfg_spi_sd[2]
set_location_assignment PIN_D19 -to cfg_spi_sd[1]
set_location_assignment PIN_D18 -to cfg_spi_sd[0]
set_location_assignment PIN_K19 -to cfg_spi_cs_n
set_location_assignment PIN_P3 -to IO_L12N_T1_MRCC_35
set_location_assignment PIN_N2 -to IO_L10P_T1_AD15P_35
set_location_assignment PIN_M2 -to IO_L9P_T1_DQS_AD7P_35
set_location_assignment PIN_M3 -to IO_L8N_T1_AD14N_35
set_location_assignment PIN_K3 -to IO_L7N_T1_AD6N_35
set_location_assignment PIN_J3 -to IO_L7P_T1_AD6P_35
set_location_assignment PIN_L1 -to IO_L6N_T0_VREF_35
set_location_assignment PIN_H2 -to xgs_sdin
set_location_assignment PIN_P1 -to xgs_monitor[0]
set_location_assignment PIN_N1 -to xgs_monitor[1]
set_location_assignment PIN_M1 -to xgs_monitor[2]
set_location_assignment PIN_N3 -to ref_clk
set_location_assignment PIN_L2 -to xgs_trig_rd
set_location_assignment PIN_L3 -to xgs_trig_int
set_location_assignment PIN_H1 -to xgs_sdout
set_location_assignment PIN_J1 -to xgs_sclk
set_location_assignment PIN_G2 -to xgs_reset_n
set_location_assignment PIN_K2 -to xgs_fwsi_en
set_location_assignment PIN_J2 -to xgs_cs_n
set_location_assignment PIN_G3 -to xgs_clk_pll_en
set_location_assignment PIN_V8 -to IO_L14N_T2_SRCC_34
set_location_assignment PIN_U8 -to IO_L14P_T2_SRCC_34
set_location_assignment PIN_V4 -to IO_L11N_T1_SRCC_34
set_location_assignment PIN_U4 -to IO_L11P_T1_SRCC_34
set_location_assignment PIN_U2 -to IO_L9N_T1_DQS_34
set_location_assignment PIN_U3 -to IO_L9P_T1_DQS_34
set_location_assignment PIN_W2 -to xgs_hispi_sdata_n[5]
set_location_assignment PIN_V2 -to xgs_hispi_sdata_p[5]
set_location_assignment PIN_V7 -to xgs_hispi_sdata_n[4]
set_location_assignment PIN_U7 -to xgs_hispi_sdata_p[4]
set_location_assignment PIN_T2 -to xgs_hispi_sdata_n[3]
set_location_assignment PIN_R2 -to xgs_hispi_sdata_p[3]
set_location_assignment PIN_T3 -to IO_L2N_T0_34
set_location_assignment PIN_R3 -to IO_L2P_T0_34
set_location_assignment PIN_V5 -to xgs_hispi_sdata_n[2]
set_location_assignment PIN_U5 -to xgs_hispi_sdata_p[2]
set_location_assignment PIN_U1 -to xgs_hispi_sdata_n[1]
set_location_assignment PIN_T1 -to xgs_hispi_sdata_p[1]
set_location_assignment PIN_W3 -to xgs_hispi_sdata_n[0]
set_location_assignment PIN_V3 -to xgs_hispi_sdata_p[0]
set_location_assignment PIN_W6 -to xgs_hispi_sclk_n[3]
set_location_assignment PIN_W7 -to xgs_hispi_sclk_p[3]
set_location_assignment PIN_W4 -to xgs_hispi_sclk_n[2]
set_location_assignment PIN_W5 -to xgs_hispi_sclk_p[2]
set_location_assignment PIN_A10 -to MGTREFCLK1N_216
set_location_assignment PIN_B10 -to MGTREFCLK1P_216
set_location_assignment PIN_D1 -to pcie_tx_n[1]
set_location_assignment PIN_D2 -to pcie_tx_p[1]
set_location_assignment PIN_A2 -to pcie_tx_n[0]
set_location_assignment PIN_B2 -to pcie_tx_p[0]
set_location_assignment PIN_A4 -to pcie_rx_n[1]
set_location_assignment PIN_B4 -to pcie_rx_p[1]
set_location_assignment PIN_A6 -to pcie_rx_n[0]
set_location_assignment PIN_B6 -to pcie_rx_p[0]
set_location_assignment PIN_A8 -to pcie_clk_n
set_location_assignment PIN_B8 -to pcie_clk_p
set_location_assignment PIN_G7 -to MGTAVTT_G7
set_location_assignment PIN_E2 -to MGTAVTT_E2
set_location_assignment PIN_C5 -to MGTAVTT_C5
set_location_assignment PIN_B1 -to MGTAVTT_B1
set_location_assignment PIN_H9 -to MGTAVCC_H9
set_location_assignment PIN_G9 -to MGTAVCC_G9
set_location_assignment PIN_F3 -to MGTAVCC_F3
set_location_assignment PIN_E1 -to MGTAVCC_E1
set_location_assignment PIN_C1 -to MGTAVCC_C1
set_location_assignment PIN_C7 -to MGTRREF_216
